#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ranger
Version  : 0.10.1
Release  : 13
URL      : https://cran.r-project.org/src/contrib/ranger_0.10.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ranger_0.10.1.tar.gz
Summary  : A Fast Implementation of Random Forests
Group    : Development/Tools
License  : GPL-3.0
Requires: R-ranger-lib
Requires: R-Rcpp
Requires: R-RcppEigen
BuildRequires : R-Rcpp
BuildRequires : R-RcppEigen
BuildRequires : clr-R-helpers

%description
dimensional data. Ensembles of classification, regression, survival and
          probability prediction trees are supported. Data from genome-wide association
          studies can be analyzed efficiently. In addition to data frames, datasets of
          class 'gwaa.data' (R package 'GenABEL') and 'dgCMatrix' (R package 'Matrix') 
          can be directly analyzed.

%package lib
Summary: lib components for the R-ranger package.
Group: Libraries

%description lib
lib components for the R-ranger package.


%prep
%setup -q -c -n ranger

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528186392

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1528186392
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ranger
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ranger
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ranger
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library ranger|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ranger/CITATION
/usr/lib64/R/library/ranger/DESCRIPTION
/usr/lib64/R/library/ranger/INDEX
/usr/lib64/R/library/ranger/Meta/Rd.rds
/usr/lib64/R/library/ranger/Meta/features.rds
/usr/lib64/R/library/ranger/Meta/hsearch.rds
/usr/lib64/R/library/ranger/Meta/links.rds
/usr/lib64/R/library/ranger/Meta/nsInfo.rds
/usr/lib64/R/library/ranger/Meta/package.rds
/usr/lib64/R/library/ranger/NAMESPACE
/usr/lib64/R/library/ranger/NEWS
/usr/lib64/R/library/ranger/R/ranger
/usr/lib64/R/library/ranger/R/ranger.rdb
/usr/lib64/R/library/ranger/R/ranger.rdx
/usr/lib64/R/library/ranger/help/AnIndex
/usr/lib64/R/library/ranger/help/aliases.rds
/usr/lib64/R/library/ranger/help/paths.rds
/usr/lib64/R/library/ranger/help/ranger.rdb
/usr/lib64/R/library/ranger/help/ranger.rdx
/usr/lib64/R/library/ranger/html/00Index.html
/usr/lib64/R/library/ranger/html/R.css
/usr/lib64/R/library/ranger/include/ranger.h
/usr/lib64/R/library/ranger/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/ranger/libs/ranger.so
/usr/lib64/R/library/ranger/libs/ranger.so.avx2
/usr/lib64/R/library/ranger/libs/ranger.so.avx512
